services:
  - docker

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed kennedyuche/udagram-api-feed:v1
  - docker tag udagram-api-user kennedyuche/udagram-api-user:v1
  - docker tag udagram-frontend kennedyuche/udagram-frontend:v1
  - docker tag reverseproxy kennedyuche/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kennedyuche/udagram-api-feed:v1
  - docker push kennedyuche/udagram-api-user:v1
  - docker push kennedyuche/udagram-frontend:v1
  - docker push kennedyuche/reverseproxy:v1
